version: '3.8'

services:
  docchat:
    build: .
    container_name: docchat
    ports:
      - "7860:7860"
      - "11434:11434"
    volumes:
      - ./data:/app/data
      - ./Backend/rag/faiss_index:/app/Backend/rag/faiss_index
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_models:

