services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  docchat:
    build: .
    container_name: docchat
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./meta_data/faiss_index:/app/meta_data/faiss_index
      - ./meta_data/output:/app/meta_data/output
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - GRADIO_SERVER_NAME=0.0.0.0
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_models: