services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11435:11434"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  docchat:
    build: .
    container_name: docchat
    ports:
      - "7862:7860"
    volumes:
      - ./data:/app/data
      - ./meta_data/faiss_index:/app/meta_data/faiss_index
      - ./meta_data/output:/app/meta_data/output
      - /home/abdallah/doc-chat/doc-chat:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - GRADIO_SERVER_NAME=0.0.0.0
      - MODEL_NAME=${MODEL_NAME:-gpt-oss:20b}
      - CHECK_MISSING=${CHECK_MISSING:-True}
    depends_on:
      - ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_models: